spring.application.name=backend

server.port=8080

# postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/messaging_db
spring.datasource.username=postgres
spring.datasource.password=fuentes024!
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# jwt
jwt.secret=f5594a80bf91a612321b53dcf6e565916f877ead92eceb05592938b16a9b0290
jwt.expiration=86400000

# almacenamiento local
app.uploads.dir=uploads/photos
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# log
logging.level.com.messaging=DEBUG